### ISSUE TITLE
Local Intergration - no need to pay for OpenAI API key.

### ISSUE THREAD

**Issue by chewtoys** [DogeLord081/OneReality#1]
Webui
https://github.com/oobabooga/text-generation-webui

13 billion CHATGPT model
https://huggingface.co/TheBloke/stable-vicuna-13B-GPTQ

Text to Speech
https://github.com/JonathanFly/bark

Would like to see a integration with these tools that runs locally without the need of OPENAI API key.

**Comment by DogeLord081** [comment]
Oh yea, you're that guy from reddit. I'll definitely try to implement this soon! It would be very helpful

**Comment by DogeLord081** [comment]
Done, except for whisper bc local whisper.cpp isn't very good, but will look into free stt options in the future
