### ISSUE TITLE
Typo for setup.py

### ISSUE THREAD

**Issue by ghost** [DogeLord081/OneReality#13]
### For line 35 the original code show : 
`snapshot_download(repo_id="TheBloke/dolphin-2.1-mistral-7B-GPTQ", local_dir=f"{y} + \dolphin-2.1-mistral-7B-GPTQ", local_dir_use_symlinks=False)`
Which will cause program to create a new folder 

### I think the correct code should be as follow:
`snapshot_download(repo_id="TheBloke/dolphin-2.1-mistral-7B-GPTQ", local_dir=f"{y}" + "\dolphin-2.1-mistral-7B-GPTQ", local_dir_use_symlinks=False)`
So that the directory won't show error.

**Comment by DogeLord081** [comment]
Thanks, fixed. Sorry I didn't see this earlier, I didn't get any notification for some reason
