### ISSUE TITLE
nvida error 

### ISSUE THREAD

**Issue by sickness396** [DogeLord081/OneReality#3]
can anyone help me with this

**Comment by DogeLord081** [comment]
> can anyone help me with this

Whats the issue?

**Comment by DylanLammens** [comment]
nvidea give an error as soon as i open it it says that nvidea can't find run.exe

**Comment by DogeLord081** [comment]
Mind attaching a screenshot of your OneReality folder?

**Comment by Shaikhyunus7039** [comment]
> nvidea give an error as soon as i open it it says that nvidea can't find run.exe

same, did u fix it ?

**Comment by DogeLord081** [comment]
> > nvidea give an error as soon as i open it it says that nvidea can't find run.exe
> 
> same, did u fix it ?

Can you also attach a screenshot of your OneReality folder?
