### ISSUE TITLE
Voicebox text to speech

### ISSUE THREAD

**Issue by NOOB-3301** [DogeLord081/OneReality#4]
If you don't mind, can you provide the code for only text to speech,how do you send the request to the voicebox engine??

**Comment by DogeLord081** [comment]
Sorry! I didn't see this issue somehow until now, this is the code for voicevox:

```
import requests

params_encoded = urllib.parse.urlencode({'text': "WHAT_YOU_WANT_TO_BE_SPOKEN_HERE", 'speaker': 20})
request = requests.post(f'http://127.0.0.1:50021/audio_query?{params_encoded}')
params_encoded = urllib.parse.urlencode({'speaker': 20, 'enable_interrogative_upspeak': True})
request = requests.post(f'http://127.0.0.1:50021/synthesis?{params_encoded}', json=request.json())
```

Also, before running the code you need to download and start the voicevox engine .exe file which should be `run.exe` in the voicevox folder as shown in 4 of README-OLD (Voicevox).MD

**Comment by NOOB-3301** [comment]
Yeah I managed to figure it out..but forgot to close it 
Btw thanks 👍👍👍👍

**Comment by NOOB-3301** [comment]
> Sorry! I didn't see this issue somehow until now, this is the code for voicevox:
> 
> ```
> import requests
> 
> params_encoded = urllib.parse.urlencode({'text': "WHAT_YOU_WANT_TO_BE_SPOKEN_HERE", 'speaker': 20})
> request = requests.post(f'http://127.0.0.1:50021/audio_query?{params_encoded}')
> params_encoded = urllib.parse.urlencode({'speaker': 20, 'enable_interrogative_upspeak': True})
> request = requests.post(f'http://127.0.0.1:50021/synthesis?{params_encoded}', json=request.json())
> ```
> 
> Also, before running the code you need to download and start the voicevox engine .exe file which should be `run.exe` in the voicevox folder as shown in 4 of README-OLD (Voicevox).MD
