### ISSUE TITLE
some kind of syntex error while starting

### ISSUE THREAD

**Issue by yasharyan456** [DogeLord081/OneReality#5]
![not cool](https://github.com/DogeLord081/OneReality/assets/140939336/6edd098a-189d-4194-a4cd-df847d099552)

**Comment by mohit-kumar-singh55** [comment]
> 

@yasharyan456 
Don't use double-quotes **""TWICE""**
replace that line with -
`chat_log = r"C:\Users\Aryan familys laptop\Downloads\OneReality-main\OneReality-main\conversation.txt"`
